#Floss_Plotting.R
#Use the results generated by Floss_Reference.sh and Floss_Distribution.sh

CurrPath <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(CurrPath)

AllGeneCDSCountFile <- "Demo.AllGeneCDSPi.FDis.summary.count"
AllGeneCDSFreqFile <- "Demo.AllGeneCDSPi.FDis.summary.freq"
RefFile <- "Demo.mRNARef.freq"
SmRNAFile <- "Demo.SmRNA.FDis.summary.freq"
RPFpiFile <- "Demo.piRNA.FDis.summary.freq"

OutputFile <- "FLOSS.Plot.pdf"
OutputDatamRNA <- "FLOSSScores.Lizard.mRNA.csv"
OutputpiRNA <- "FLOSSScores.Lizard.piRNARPF.csv"
OutputSm <- "FLOSSScores.Lizard.SmRNA.csv"

#Pre-processing
Counts <- read.table(AllGeneCDSCountFile,header = T,check.names = F,row.names = 1)
Data <- read.table(AllGeneCDSFreqFile,header = T,check.names = F,row.names = 1)
colnames(Counts) = c("C26","C27","C28","C29","C30","C31","C32")
colnames(Data) = c("L26","L27","L28","L29","L30","L31","L32")
Ref <- read.table(RefFile,header = F,col.names = c("Length","Freq"))
SmRNA <- read.table(SmRNAFile,header = T,check.names = F,row.names = 1)
colnames(SmRNA) = c("S26","S27","S28","S29","S30","S31","S32")
RPFpi <- read.table(RPFpiFile,header = T,check.names = F,row.names = 1)
colnames(RPFpi) = c("S26","S27","S28","S29","S30","S31","S32")

#Organize data
Counts$SumCounts <- apply(Counts,1,sum)
Data$R26 <- Ref$Freq[1]
Data$R27 <- Ref$Freq[2]
Data$R28 <- Ref$Freq[3]
Data$R29 <- Ref$Freq[4]
Data$R30 <- Ref$Freq[5]
Data$R31 <- Ref$Freq[6]
Data$R32 <- Ref$Freq[7]

#Run FLOSS
Data$Floss <- (abs(Data$L26-Data$R26) + abs(Data$L27-Data$R27) + abs(Data$L28-Data$R28) + abs(Data$L29-Data$R29) +
  abs(Data$L30-Data$R30) + abs(Data$L31-Data$R31) + abs(Data$L32-Data$R32))/200
Data$SumCounts <- Counts$SumCounts

#Separate classes
Data$Type <- c(rep("mRNA",19176),rep("piRNA",100))
Data$LogSumCounts <- log10(Data$SumCounts+1)
New <- tail(Data,100)

#Run FLOSS on smRNA control, Prepach
SmRNA$Floss <- (abs(SmRNA$S26-New$R26) + abs(SmRNA$S27-New$R27) + abs(SmRNA$S28-New$R28) + abs(SmRNA$S29-New$R29) +
                  abs(SmRNA$S30-New$R30) + abs(SmRNA$S31-New$R31) + abs(SmRNA$S32-New$R32))/200

#Plotting
Xmin=0
Xmax=4
mRNA <- subset(Data,Data$Type == "mRNA" )
piRNA_all <- subset(Data,Data$Type=="piRNA")
piRNA <- subset(Data,Data$Type == "piRNA")
SmRNAFloss <- SmRNA
SmRNAFloss$LogSumCounts <- piRNA_all$LogSumCounts
SmRNAFloss$Type = "Small"
SmRNAFloss <- subset(SmRNAFloss,SmRNAFloss$LogSumCounts > log10(23))

plot(mRNA[,c("LogSumCounts","Floss")],pch=20,cex=0.3,xlim=c(Xmin,Xmax),ylim=c(0,1),xlab="Raw Reads",ylab="FLOSS",bty="n", tck=0.015,xaxt='n',las=2)
par(new=T)
plot(piRNA[,c("LogSumCounts","Floss")],pch=20,cex=0.7,col="red",xlim=c(Xmin,Xmax),ylim=c(0,1),xlab="",ylab="",ann=FALSE,xaxt='n',yaxt='n',bty="n")
par(new=T)
plot(SmRNAFloss[,c("LogSumCounts","Floss")],pch=20,cex=0.7,col="dodgerblue",xlim=c(Xmin,Xmax),ylim=c(0,1),xlab="",ylab="",ann=FALSE,xaxt='n',yaxt='n',bty="n")

legend(c("RPF from mRNA","RPF from piRNA precursor","piRNA"),
       x = 2.1,y = 1,text.col = c("black","red","dodgerblue"),bty = "n",cex=1)
axis(side = 1,at = 0:4,labels = c(expression('10'^0),expression('10'^1),expression('10'^2),expression('10'^3),expression('10'^4)),tck = 0.015)
Intervals=10
Max=3.8
Min=0.28
Step=(Max-Min)/Intervals
Curve=data.frame()
for (i in 1:Intervals){
  RangeL=Min+Step*(i-1)
  RangeR=Min+Step*i
  Middle=(RangeL+RangeR)/2
  print(paste(RangeL,RangeR))
  data=subset(Data,Data$SumCounts<10^RangeR & Data$SumCounts>=10^RangeL)
  stats=summary(data$Floss)
  UpperOutlier=stats[5]+(stats[5]-stats[2])*1.5
  print(UpperOutlier)
  Curve[i,1]=Middle
  Curve[i,2]=UpperOutlier
}
par(new=T)
lo <- loess(Curve$V2~Curve$V1)
plot(Curve$V1,predict(lo),pch=20,xlim=c(Xmin,Xmax),ylim=c(0,1),col="darkorchid1",type="l",lwd=3,xlab="",ylab="",ann=FALSE,xaxt='n',yaxt='n',bty="n")

#Output table:
#All data:
write.csv(Data[,c("Type","SumCounts","Floss")],file = OutputDatamRNA)
write.csv(piRNA[,c("Type","SumCounts","Floss")],file = OutputpiRNA)
write.csv(SmRNAFloss[,c("Type","LogSumCounts","Floss")],file = OutputSm)